### ISSUE TITLE
About RetryHelper

### ISSUE THREAD

**Issue by juneswang2016** [googleads/adwords-alerting#5]
When migrating to API v201705, why remove class RetryHelper.java?

**Comment by chenzhuo914** [comment]
Because it's now using Java client library's [RateLimiter extension](https://github.com/googleads/googleads-java-lib/tree/master/extensions/adwords_rate_limiter), which supersedes its own RetryHelper implementation!

In the pom.xml:
```
    <dependency>
      <groupId>com.google.api-ads</groupId>
      <artifactId>adwords-extension-ratelimiter</artifactId>
      <version>0.1.0</version>
    </dependency>
```

In com.google.api.ads.adwords.awalerting.util.AdWordsServicesUtil.java:
```
  private static final AdWordsServicesWithRateLimiter instance =
      new AdWordsServicesWithRateLimiter(AdWordsServices.getInstance());
```
